version: "3"
services:
  traefik:
    container_name: traefik
    image: traefik:v1.7.16
    hostname: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - traefik_proxy
    ports:
      - 80:80
      - 443:443
      - 9090:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      traefik.enable: "true"
      traefik.backend: "traefik"
      traefik.frontend.rule: "Host:traefik.${DOMAINNAME}"
      traefik.port: "8080"
      traefik.docker.network: "traefik_proxy"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.STSSeconds: "315360000"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.SSLHost: "${DOMAINNAME}"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.frameDeny: "true"
      traefik.frontend.auth.basic.users: "${HTTP_USERNAME}:${HTTP_PASSWORD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKERCONFDIR}/traefik:/etc/traefik
      - ${DOCKERSHAREDDIR}:/shared
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - traefik_proxy
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERCONFDIR}/portainer:/data
      - ${DOCKERSHAREDDIR}:/shared
    labels:
      traefik.enable: "true"
      traefik.backend: "portainer"
      traefik.protocol: "http"
      traefik.port: "9000"
      traefik.frontend.rule: "Host:portainer.${DOMAINNAME}"
      traefik.frontend.headers.SSLHost: "portainer.${DOMAINNAME}"
      traefik.docker.network: "traefik_proxy"
      traefik.frontend.passHostHeader: "true"
      traefik.frontend.headers.SSLForceHost: "true"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.STSSeconds: "315360000"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.customResponseHeaders: "X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      traefik.frontend.headers.frameDeny: "true"
      traefik.frontend.headers.customFrameOptionsValue: "allow-from https:${DOMAINNAME}"
  unifi-controller:
    container_name: unifi-controller
    hostname: unifi
    image: jacobalberty/unifi:latest
    restart: always
    environment:
      - UNIFI_UID=${PUID}
      - UNIFI_GID=${PGID}
      - RUNAS_UID0=false
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/unifi:/unifi
    networks:
      - default
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
  bitwarden:
    container_name: bitwarden
    hostname: bitwarden
    image: bitwardenrs/server
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true
    networks:
      - traefik_proxy
    ports:
      - 9292:80
      - 3012:3012
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/bitwarden:/data
    - ${DOCKERSHAREDDIR}:/shared
    labels:
      traefik.enable: "true"
      traefik.web.frontend.rule: "Host:bitwarden.${DOMAINNAME}"
      traefik.web.port: "80"
      traefik.hub.frontend.rule: "Host:bitwarden.${DOMAINNAME}Path:/notifications/hub"
      traefik.hub.protocol: "ws"
      traefik.hub.port: "3012"
      traefik.docker.network: "traefik_proxy"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.STSSeconds: "315360000"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.SSLHost: "${DOMAINNAME}"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.frameDeny: "true"
  radarr:
    container_name: radarr
    hostname: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    networks:
      - traefik_proxy
    ports:
    - 7878:7878
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/radarr:/config
    - ${DOCKERSHAREDDIR}:/shared
    - ${MEDIADIR_DOWNLOAD}:/data
    - ${MEDIADIR_DOWNLOAD}:/downloads
    - ${MEDIADIR_MOVIES}:/movies
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:radarr.${DOMAINNAME}"
      traefik.port: "7878"
      traefik.docker.network: "traefik_proxy"
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.frontend.headers.STSSeconds: "315360000"
      traefik.frontend.headers.browserXSSFilter: "true"
      traefik.frontend.headers.contentTypeNosniff: "true"
      traefik.frontend.headers.forceSTSHeader: "true"
      traefik.frontend.headers.SSLHost: "${DOMAINNAME}"
      traefik.frontend.headers.STSIncludeSubdomains: "true"
      traefik.frontend.headers.STSPreload: "true"
      traefik.frontend.headers.frameDeny: "true"
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge